import { useState, useEffect, useCallback, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { api, type KnowledgeEntry } from "@/lib/tauri-api"
import { useToast } from "@/hooks/use-toast"
import { cn } from "@/lib/utils"
import { X, Loader2, Sparkles } from "lucide-react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"

const CATEGORIES = [
  { key: "patterns",   label: "最佳模式" },
  { key: "decisions",  label: "决策记录" },
  { key: "pitfalls",   label: "踩坑经验" },
  { key: "metrics",    label: "指标设计" },
  { key: "playbooks",  label: "打法手册" },
  { key: "insights",   label: "产品洞察" },
]

export function ToolKnowledgePage() {
  const { toast } = useToast()
  const [entries, setEntries] = useState<KnowledgeEntry[]>([])
  const [activeCategory, setActiveCategory] = useState("pitfalls")
  const [showAdd, setShowAdd] = useState(false)
  const [newTitle, setNewTitle] = useState("")
  const [newContent, setNewContent] = useState("")
  const [saving, setSaving] = useState(false)
  const [loading, setLoading] = useState(true)
  const [searchQuery, setSearchQuery] = useState("")
  const [searchResults, setSearchResults] = useState<KnowledgeEntry[] | null>(null)
  const [drawerEntry, setDrawerEntry] = useState<KnowledgeEntry | null>(null)
  const [drawerContent, setDrawerContent] = useState("")
  const [drawerLoading, setDrawerLoading] = useState(false)

  // T4: cleanup auto-cards dialog
  const [cleanupOpen, setCleanupOpen] = useState(false)
  const [cleanupConfidence, setCleanupConfidence] = useState<"low" | "medium" | "high">("low")
  const [cleanupAction, setCleanupAction] = useState<"archive" | "delete">("archive")
  const [cleanupRunning, setCleanupRunning] = useState(false)

  const autoStats = useMemo(() => {
    const all = entries.filter((e) => e.source === "auto" || e.autoGenerated)
    const byConfidence: Record<string, number> = { low: 0, medium: 0, high: 0, unknown: 0 }
    for (const e of all) {
      const c = e.confidence ?? "unknown"
      byConfidence[c] = (byConfidence[c] ?? 0) + 1
    }
    return { total: all.length, byConfidence }
  }, [entries])

  const loadEntries = useCallback(async () => {
    try {
      const data = await api.listKnowledge()
      setEntries(data)
    } catch (err) {
      console.error(err)
      toast("知识库加载失败", "error")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { loadEntries() }, [loadEntries])

  const handleCleanup = useCallback(async () => {
    setCleanupRunning(true)
    try {
      const result = await api.cleanupAutoKnowledge({
        maxConfidence: cleanupConfidence,
        action: cleanupAction,
      })
      toast(
        `${cleanupAction === "delete" ? "删除" : "归档"}成功：${result.processed} 条`,
        result.failed.length > 0 ? "warning" : "success",
      )
      setCleanupOpen(false)
      await loadEntries()
    } catch (err) {
      console.error("[Knowledge] cleanup:", err)
      toast(`清理失败：${String(err)}`, "error")
    } finally {
      setCleanupRunning(false)
    }
  }, [cleanupAction, cleanupConfidence, loadEntries, toast])

  // Debounced search
  useEffect(() => {
    if (!searchQuery.trim()) {
      setSearchResults(null)
      return
    }
    const timer = setTimeout(() => {
      api.searchKnowledge(searchQuery).then(setSearchResults).catch((err) => { console.error("[Knowledge]", err); toast("搜索失败", "error") })
    }, 300)
    return () => clearTimeout(timer)
  }, [searchQuery])

  const filtered = entries.filter((e) => e.category === activeCategory)

  const handleAdd = useCallback(async () => {
    if (!newTitle.trim() || !newContent.trim()) return
    setSaving(true)
    try {
      await api.addKnowledge({ category: activeCategory, title: newTitle.trim(), content: newContent.trim() })
      setNewTitle("")
      setNewContent("")
      setShowAdd(false)
      await loadEntries()
    } catch (err) {
      console.error(err)
      toast("添加知识条目失败", "error")
    } finally {
      setSaving(false)
    }
  }, [activeCategory, newTitle, newContent, loadEntries])

  const handleDelete = useCallback(async (category: string, id: string) => {
    try {
      await api.deleteKnowledge(category, id)
      await loadEntries()
    } catch (err) {
      console.error("Failed to delete entry:", err)
      toast("删除条目失败", "error")
    }
  }, [loadEntries])

  const handleOpenDrawer = useCallback(async (entry: KnowledgeEntry) => {
    setDrawerEntry(entry)
    setDrawerContent("")
    setDrawerLoading(true)
    try {
      const content = await api.getKnowledgeContent(entry.category, entry.id)
      setDrawerContent(content)
    } catch (err) {
      console.error("[Knowledge]", err)
      setDrawerContent("_无法加载内容_")
    } finally {
      setDrawerLoading(false)
    }
  }, [])

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <span className="text-[13px] text-[var(--text-secondary)]">加载中...</span>
      </div>
    )
  }

  return (
    <div className="mx-auto w-full max-w-[860px]">
      <div className="mb-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h1 className="text-base font-semibold text-[var(--text-primary)]">知识库</h1>
          <span className="text-sm text-[var(--text-secondary)]">产品知识库</span>
        </div>
        <div className="flex items-center gap-2">
          {autoStats.total > 0 && (
            <Button variant="ghost" size="sm" onClick={() => setCleanupOpen(true)}>
              <Sparkles className="size-3.5 mr-1" />
              清理 auto 卡片（{autoStats.total}）
            </Button>
          )}
          <Button variant="ghost" size="sm" onClick={() => setShowAdd(!showAdd)}>
            {showAdd ? "取消" : "+ 添加"}
          </Button>
        </div>
      </div>
      <div className="h-px bg-[var(--border)]" />

      {/* 搜索框 */}
      <div className="mt-4">
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="搜索知识库..."
          className={cn(
            "w-full rounded-lg h-9 px-3 text-sm",
            "bg-transparent border border-[var(--border)]",
            "placeholder:text-[var(--text-secondary)]",
            "outline-none focus:border-[var(--accent-color)] transition-[border-color]"
          )}
        />
      </div>

      {/* 分类标签：搜索时隐藏 */}
      {!searchResults && (
        <div className="mt-4 border-b border-[var(--border)] flex flex-wrap gap-1">
          {CATEGORIES.map((cat) => {
            const count = entries.filter((e) => e.category === cat.key).length
            return (
              <button
                key={cat.key}
                onClick={() => setActiveCategory(cat.key)}
                className={cn(
                  "px-3 py-1.5 text-xs transition-colors",
                  activeCategory === cat.key
                    ? "border-b-2 border-[var(--accent-color)] text-[var(--text-primary)] font-medium"
                    : "border-b-2 border-transparent text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                )}
              >
                {cat.label} {count > 0 && `(${count})`}
              </button>
            )
          })}
        </div>
      )}

      {/* 添加表单 */}
      {showAdd && (
        <div className="mt-4 rounded-lg border border-[var(--accent-color)]/30 p-4">
          <div className="mb-3">
            <input
              type="text"
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              placeholder="标题"
              className={cn(
                "w-full rounded-lg h-9 px-3 text-sm",
                "bg-transparent border border-[var(--border)]",
                "placeholder:text-[var(--text-secondary)]",
                "outline-none focus:border-[var(--accent-color)] transition-[border-color]"
              )}
            />
          </div>
          <textarea
            value={newContent}
            onChange={(e) => setNewContent(e.target.value)}
            placeholder="内容（支持 Markdown）"
            rows={4}
            className={cn(
              "w-full rounded-lg px-3 py-2 text-sm",
              "bg-transparent border border-[var(--border)]",
              "placeholder:text-[var(--text-secondary)]",
              "outline-none resize-none focus:border-[var(--accent-color)] transition-[border-color]"
            )}
          />
          <div className="mt-2 flex justify-end">
            <Button variant="primary" size="sm" onClick={handleAdd} disabled={saving || !newTitle.trim() || !newContent.trim()}>
              {saving ? "保存中..." : "保存"}
            </Button>
          </div>
        </div>
      )}

      {/* 条目列表 */}
      <div className="mt-4 space-y-2">
        {searchResults !== null ? (
          searchResults.length === 0 ? (
            <p className="py-8 text-center text-sm text-[var(--text-secondary)]">
              未找到相关知识
            </p>
          ) : (
            searchResults.map((entry) => (
              <div key={`${entry.category}-${entry.id}`} className="group rounded-lg border border-[var(--border)] p-4 hover:border-[var(--accent-color)]/40 transition-colors cursor-pointer" onClick={() => handleOpenDrawer(entry)}>
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 mb-0.5">
                      <span className="text-[10px] text-[var(--text-secondary)] bg-[var(--secondary)] px-1.5 py-0.5 rounded">
                        {CATEGORIES.find((c) => c.key === entry.category)?.label ?? entry.category}
                      </span>
                      {entry.source === "auto" && (
                        <span className="text-[9px] text-[var(--accent-color)] bg-[var(--accent-light)] px-1.5 py-0.5 rounded font-medium">
                          自动提取
                        </span>
                      )}
                    </div>
                    <p className="font-medium text-sm text-[var(--text-primary)]">{entry.title}</p>
                    <p className="mt-1 text-xs text-[var(--text-secondary)] line-clamp-2">
                      {entry.content.replace(/^#[^\n]+\n+/, "").slice(0, 120)}
                    </p>
                  </div>
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDelete(entry.category, entry.id) }}
                    className="shrink-0 text-[10px] text-[var(--text-secondary)] opacity-0 group-hover:opacity-100 hover:text-[var(--destructive)] transition-opacity"
                  >
                    删除
                  </button>
                </div>
              </div>
            ))
          )
        ) : filtered.length === 0 ? (
          <p className="py-8 text-center text-sm text-[var(--text-secondary)]">
            该分类暂无条目，点击右上角「+ 添加」记录第一条经验
          </p>
        ) : (
          filtered.map((entry) => (
            <div key={entry.id} className="group rounded-lg border border-[var(--border)] p-4 hover:border-[var(--accent-color)]/40 transition-colors cursor-pointer" onClick={() => handleOpenDrawer(entry)}>
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <p className="font-medium text-sm text-[var(--text-primary)]">{entry.title}</p>
                    {entry.source === "auto" && (
                      <span className="text-[9px] text-[var(--accent-color)] bg-[var(--accent-light)] px-1.5 py-0.5 rounded font-medium">
                        自动提取
                      </span>
                    )}
                  </div>
                  <p className="mt-1 text-xs text-[var(--text-secondary)] line-clamp-2">
                    {entry.content.replace(/^#[^\n]+\n+/, "").slice(0, 120)}
                  </p>
                </div>
                <button
                  onClick={(e) => { e.stopPropagation(); handleDelete(entry.category, entry.id) }}
                  className="shrink-0 text-[10px] text-[var(--text-secondary)] opacity-0 group-hover:opacity-100 hover:text-[var(--destructive)] transition-opacity"
                >
                  删除
                </button>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Knowledge detail drawer */}
      {drawerEntry && (
        <div className="fixed inset-0 z-50 flex" role="dialog" aria-modal="true" aria-labelledby="dialog-title-knowledge-drawer">
          {/* Backdrop */}
          <div
            className="flex-1 bg-black/20 backdrop-blur-[2px]"
            onClick={() => setDrawerEntry(null)}
          />
          {/* Panel */}
          <div className="w-[480px] max-w-[90vw] bg-[var(--background)] border-l border-[var(--border)] flex flex-col shadow-[var(--shadow-xl)] animate-in slide-in-from-right duration-200">
            <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--border)]">
              <div className="min-w-0 flex-1">
                <h2 id="dialog-title-knowledge-drawer" className="text-[15px] font-semibold text-[var(--text-primary)] truncate">
                  {drawerEntry.title}
                </h2>
                <span className="text-[12px] text-[var(--text-tertiary)]">
                  {CATEGORIES.find(c => c.key === drawerEntry.category)?.label ?? drawerEntry.category}
                </span>
              </div>
              <button
                onClick={() => setDrawerEntry(null)}
                aria-label="关闭"
                className="ml-3 shrink-0 text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors"
              >
                <X className="size-4" />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto px-5 py-4">
              {drawerLoading ? (
                <div className="flex items-center gap-2 text-sm text-[var(--text-tertiary)]">
                  <Loader2 className="size-4 animate-spin" />
                  加载中...
                </div>
              ) : (
                <div className="prose prose-sm max-w-none">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {drawerContent}
                  </ReactMarkdown>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* T4: cleanup auto-cards dialog */}
      {cleanupOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-[4px]"
          style={{ animation: "fadeIn 150ms var(--ease-decelerate)" }}
          onClick={(e) => { if (e.target === e.currentTarget && !cleanupRunning) setCleanupOpen(false) }}
        >
          <div
            role="dialog"
            aria-modal="true"
            className="w-full max-w-[440px] rounded-xl bg-[var(--background)] p-6 shadow-[var(--shadow-xl)]"
            style={{ animation: "fadeInUp 200ms var(--ease-decelerate)" }}
          >
            <h2 className="text-base font-semibold text-[var(--text-primary)] mb-1">清理 auto 卡片</h2>
            <p className="text-xs leading-relaxed text-[var(--text-tertiary)] mb-4">
              批量处理由 hook 自动捕获的卡片（confidence ≤ 阈值）。归档会移到 .archive/ 目录，可恢复；删除不可逆。
            </p>
            <div className="h-px bg-[var(--border)] mb-4" />

            <div className="mb-4">
              <p className="text-[12px] text-[var(--text-secondary)] mb-2">置信度阈值</p>
              <div className="flex gap-2">
                {(["low", "medium", "high"] as const).map((c) => (
                  <button
                    key={c}
                    type="button"
                    onClick={() => setCleanupConfidence(c)}
                    className={cn(
                      "flex-1 rounded-md border px-3 py-2 text-xs transition-all active:scale-[0.97] cursor-pointer",
                      cleanupConfidence === c
                        ? "border-[var(--accent-color)] bg-[var(--accent-color)]/10 text-[var(--accent-color)]"
                        : "border-[var(--border)] text-[var(--text-secondary)] hover:bg-[var(--hover-bg)]",
                    )}
                  >
                    ≤ {c}
                    <span className="block text-[10px] text-[var(--text-tertiary)]">
                      {autoStats.byConfidence.low + (c === "low" ? 0 : autoStats.byConfidence.medium) + (c === "high" ? autoStats.byConfidence.high : 0)} 条
                    </span>
                  </button>
                ))}
              </div>
            </div>

            <div className="mb-5">
              <p className="text-[12px] text-[var(--text-secondary)] mb-2">操作</p>
              <div className="flex gap-2">
                {(["archive", "delete"] as const).map((a) => (
                  <button
                    key={a}
                    type="button"
                    onClick={() => setCleanupAction(a)}
                    className={cn(
                      "flex-1 rounded-md border px-3 py-2 text-xs transition-all active:scale-[0.97] cursor-pointer",
                      cleanupAction === a
                        ? a === "delete"
                          ? "border-[var(--destructive)] bg-[var(--destructive)]/10 text-[var(--destructive)]"
                          : "border-[var(--accent-color)] bg-[var(--accent-color)]/10 text-[var(--accent-color)]"
                        : "border-[var(--border)] text-[var(--text-secondary)] hover:bg-[var(--hover-bg)]",
                    )}
                  >
                    {a === "archive" ? "归档" : "删除"}
                  </button>
                ))}
              </div>
            </div>

            <div className="flex items-center justify-end gap-2">
              <Button variant="ghost" size="sm" onClick={() => setCleanupOpen(false)} disabled={cleanupRunning}>
                取消
              </Button>
              <Button
                variant={cleanupAction === "delete" ? "destructive" : "primary"}
                size="sm"
                onClick={handleCleanup}
                disabled={cleanupRunning}
              >
                {cleanupRunning ? "处理中..." : `执行${cleanupAction === "archive" ? "归档" : "删除"}`}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
